package simulation

import (
	"encoding/json"
	"fmt"
	"math"
	"reflect"
	"strings"
	"testing"
)

func epathSQLDriverLinksFixture(t *testing.T) (epathSQLFrames, epathRealSQLModel, epathSQLModelChecks, PurposeResultBundle) {
	t.Helper()
	path, model := epathSQLModelUnitFixture(t)
	observed, err := epathReadRealSQLOracle(path)
	if err != nil {
		t.Fatal(err)
	}
	frames, err := epathCompileSQLModelFrames(path, observed.Sources, model)
	if err != nil {
		t.Fatal(err)
	}
	var checks epathSQLModelChecks
	if err := epathSQLModelDriverLinkChecks(frames, model, &checks); err != nil {
		t.Fatal(err)
	}
	// Handwritten SQL fixture: (-10 + 6) surface exchange => +4 native
	// pressure; People +1; multiplier 2*3, load3*6=18. Allocation is14.4/3.6.
	// The candidate is not generated by a production builder or by check.Want.
	graph := func(period, zone string) ([]EnergyExplanationNode, []EnergyPathLink) {
		factor := 1.0
		if period == "annual" {
			factor = 12
		}
		nodes := []EnergyExplanationNode{
			{ID: "wall", Level: "driver", DriverCategory: "surface.exterior_walls", ServiceKind: "cooling", Basis: "heat_balance_share", Unit: "kWh", ScaleDomain: "thermal", Period: period, ZoneName: zone, Value: 14.4 * factor, SourceIDs: []string{"surface-a", "surface-b"}},
			{ID: "people", Level: "driver", DriverCategory: "internal.people", ServiceKind: "cooling", Basis: "heat_balance_share", Unit: "kWh", ScaleDomain: "thermal", Period: period, ZoneName: zone, Value: 3.6 * factor, SourceIDs: []string{"people-source"}},
			{ID: "cooling", Level: "load", ServiceKind: "cooling", Basis: "reported_variable", Unit: "kWh", ScaleDomain: "thermal", Period: period, ZoneName: zone, Value: 18 * factor, SourceIDs: []string{"cooling-source"}},
		}
		links := []EnergyPathLink{
			{ID: "wall-to-cooling", FromID: "wall", ToID: "cooling", Relation: "driver_to_load", ServiceKind: "cooling", Basis: "heat_balance_share", FromUnit: "kWh", ToUnit: "kWh", Period: period, ZoneName: zone, FromValue: 14.4 * factor, ToValue: 14.4 * factor, SourceIDs: []string{"surface-a", "surface-b", "cooling-source"}},
			{ID: "people-to-cooling", FromID: "people", ToID: "cooling", Relation: "driver_to_load", ServiceKind: "cooling", Basis: "heat_balance_share", FromUnit: "kWh", ToUnit: "kWh", Period: period, ZoneName: zone, FromValue: 3.6 * factor, ToValue: 3.6 * factor, SourceIDs: []string{"people-source", "cooling-source"}},
		}
		return nodes, links
	}
	result := EnergyExplanationResult{Schema: energyExplanationSchema, Scope: EnergyExplanationScope{Kind: "building"}, AvailableZones: []string{"Office"}}
	result.Nodes, result.Links = graph("annual", "")
	zone := EnergyExplanationZoneResult{Scope: EnergyExplanationScope{Kind: "zone", ZoneName: "Office"}}
	zone.Nodes, zone.Links = graph("annual", "Office")
	for month := 1; month <= 12; month++ {
		period := fmt.Sprintf("M%d", month)
		nodes, links := graph(period, "")
		result.Periods = append(result.Periods, EnergyPeriod{ID: period, Nodes: nodes, Links: links})
		nodes, links = graph(period, "Office")
		zone.Periods = append(zone.Periods, EnergyPeriod{ID: period, Nodes: nodes, Links: links})
	}
	result.ZoneResults = []EnergyExplanationZoneResult{zone}
	for _, item := range []struct{ id, name, key string }{{"surface-a", "Surface Exchange", "Wall A"}, {"surface-b", "Surface Exchange", "Wall B"}, {"people-source", "People Gain", "Office"}, {"cooling-source", "Sensible Cooling", "Office"}, {"heating-source", "Sensible Heating", "Office"}} {
		result.Sources = append(result.Sources, EnergyDataSource{ID: item.id, SourceType: "sql_report_data", Name: item.name, KeyValue: item.key, SourceUnit: "J", NormalizedUnit: "kWh", ReportingFrequency: "Monthly"})
	}
	return frames, model, checks, PurposeResultBundle{EnergyExplanation: result}
}

func epathSQLDriverAnnualWallCheck(t *testing.T, checks epathSQLModelChecks) epathSQLModelCheck {
	t.Helper()
	for _, check := range checks.Rows {
		if check.Item.Scope == "building" && check.Item.Period == "annual" && check.DriverLink.Category == "surface.exterior_walls" && check.DriverLink.Service == "cooling" && check.Item.Target.Field == "fromValue" {
			return check
		}
	}
	t.Fatal("required annual wall link check absent")
	return epathSQLModelCheck{}
}

func TestEnergyPathRealSQLDriverLinksIndependentFramesAndAllContexts(t *testing.T) {
	frames, model, checks, bundle := epathSQLDriverLinksFixture(t)
	before, _ := json.Marshal(frames)
	for _, check := range checks.Rows {
		if err := epathCheckSQLModelDriverLink(bundle, check); err != nil {
			t.Fatalf("%s: %v", check.Want.Key, err)
		}
	}
	if len(checks.Rows) != 2*13*2*3*2 { // two scopes,13periods,2services,2categories+incoming,2ends
		t.Fatalf("incomplete endpoint roster: %d", len(checks.Rows))
	}
	wall := epathSQLDriverAnnualWallCheck(t, checks)
	if math.Abs(wall.Quantity.Value-172.8) > 1e-10 || wall.DriverLink.Load.Value != 216 || !reflect.DeepEqual(wall.DriverLink.RequiredDriverSources, []int{12, 13}) || !reflect.DeepEqual(wall.DriverLink.LoadSources, []int{10}) {
		t.Fatalf("monthly arithmetic or original source ownership changed: %#v", wall)
	}
	// Reverse insertion order without changing immutable quantities/source lists.
	reversed := frames
	reversed.Cells = map[string]*epathSQLCell{}
	keys := []string{}
	for key := range frames.Cells {
		keys = append(keys, key)
	}
	for index := len(keys) - 1; index >= 0; index-- {
		reversed.Cells[keys[index]] = frames.Cells[keys[index]]
	}
	var again epathSQLModelChecks
	if err := epathSQLModelDriverLinkChecks(reversed, model, &again); err != nil {
		t.Fatal(err)
	}
	firstJSON, _ := json.Marshal(checks.Rows)
	secondJSON, _ := json.Marshal(again.Rows)
	if string(firstJSON) != string(secondJSON) {
		t.Fatal("map insertion changed independent endpoint checks")
	}
	after, _ := json.Marshal(frames)
	if string(before) != string(after) {
		t.Fatal("link compilation mutated independent frames")
	}
}

func TestEnergyPathRealSQLDriverLinksRejectTopologyAndSourceErrors(t *testing.T) {
	_, _, checks, original := epathSQLDriverLinksFixture(t)
	check := epathSQLDriverAnnualWallCheck(t, checks)
	for _, test := range []struct {
		name string
		edit func(*EnergyExplanationResult)
	}{
		{"deleted link", func(r *EnergyExplanationResult) { r.Links = r.Links[1:] }},
		{"wrong existing endpoint", func(r *EnergyExplanationResult) { r.Links[0].ToID = "people" }},
		{"wrong service load", func(r *EnergyExplanationResult) {
			n := r.Nodes[2]
			n.ID, n.ServiceKind = "wrong-load", "heating"
			r.Nodes = append(r.Nodes, n)
			r.Links[0].ToID = n.ID
		}},
		{"wrong link service", func(r *EnergyExplanationResult) { r.Links[0].ServiceKind = "heating" }},
		{"wrong basis", func(r *EnergyExplanationResult) { r.Links[0].Basis = "reported_variable" }},
		{"duplicate ID", func(r *EnergyExplanationResult) { r.Links = append(r.Links, r.Links[0]) }},
		{"duplicate semantic branch distinct ID", func(r *EnergyExplanationResult) { l := r.Links[0]; l.ID = "other-ID"; r.Links = append(r.Links, l) }},
		{"additional positive branch", func(r *EnergyExplanationResult) {
			l := r.Links[0]
			l.ID, l.RuleID = "extra", "extra-rule"
			l.FromValue, l.ToValue = .001, .001
			r.Links = append(r.Links, l)
		}},
		{"one endpoint value differs", func(r *EnergyExplanationResult) { r.Links[0].ToValue -= .001 }},
		{"both values differ but nodes unchanged", func(r *EnergyExplanationResult) { r.Links[0].FromValue -= 1; r.Links[0].ToValue -= 1 }},
		{"thermal becomes site", func(r *EnergyExplanationResult) { r.Nodes[0].ScaleDomain = "site" }},
		{"wrong paired unit", func(r *EnergyExplanationResult) { r.Links[0].ToUnit = "MJ" }},
		{"fabricated ratio", func(r *EnergyExplanationResult) { r.Links[0].Ratio = 1 }},
		{"missing source", func(r *EnergyExplanationResult) { r.Links[0].SourceIDs[0] = "not-present" }},
		{"unrelated existing source", func(r *EnergyExplanationResult) { r.Links[0].SourceIDs[0] = "people-source" }},
		{"lost contributing surface", func(r *EnergyExplanationResult) { r.Links[0].SourceIDs = []string{"surface-a", "cooling-source"} }},
		{"missing load provenance", func(r *EnergyExplanationResult) { r.Links[0].SourceIDs = []string{"surface-a", "surface-b"} }},
		{"wrong original SQL unit", func(r *EnergyExplanationResult) { r.Sources[0].SourceUnit = "W" }},
		{"wrong normalized unit", func(r *EnergyExplanationResult) { r.Sources[0].NormalizedUnit = "J" }},
		{"wrong original frequency", func(r *EnergyExplanationResult) { r.Sources[0].ReportingFrequency = "Hourly" }},
		{"wrong original physical key", func(r *EnergyExplanationResult) { r.Sources[0].KeyValue = "Wall B" }},
		{"wrong meter semantics", func(r *EnergyExplanationResult) { r.Sources[0].IsMeter = true }},
	} {
		t.Run(test.name, func(t *testing.T) {
			// Use exact-wire test aliases, never the application compatibility reader.
			data, _ := json.Marshal(original)
			candidate, err := epathDecodeOriginalOracleCandidate(strings.NewReader(string(data)))
			if err != nil {
				t.Fatal(err)
			}
			test.edit(&candidate.EnergyExplanation)
			for index, value := range []float64{172.8, 43.2, 216} {
				if math.Abs(candidate.EnergyExplanation.Nodes[index].Value-value) > 1e-10 {
					t.Fatal("counterexample changed original node quantities")
				}
			}
			if err := epathCheckSQLModelDriverLink(candidate, check); err == nil {
				t.Fatal("link error escaped while original node numbers remained correct")
			}
		})
	}
}

func TestEnergyPathRealSQLDriverLinksDerivedLeavesAndParallelBranches(t *testing.T) {
	_, _, checks, bundle := epathSQLDriverLinksFixture(t)
	check := epathSQLDriverAnnualWallCheck(t, checks)
	r := &bundle.EnergyExplanation
	r.Sources = append(r.Sources, EnergyDataSource{ID: "arbitrary-derived-ID", SourceType: "derived_formula", InputSourceIDs: []string{"surface-a", "surface-b"}})
	r.Nodes[0].SourceIDs = []string{"arbitrary-derived-ID"}
	r.Links[0].SourceIDs = []string{"arbitrary-derived-ID", "cooling-source"}
	if err := epathCheckSQLModelDriverLink(bundle, check); err != nil {
		t.Fatalf("explicit derived SQL leaves rejected: %v", err)
	}
	r.Sources[len(r.Sources)-1].InputSourceIDs = []string{"arbitrary-derived-ID"}
	if err := epathCheckSQLModelDriverLink(bundle, check); err == nil {
		t.Fatal("cyclic derived source accepted")
	}
	r.Sources[len(r.Sources)-1].InputSourceIDs = nil
	if err := epathCheckSQLModelDriverLink(bundle, check); err == nil {
		t.Fatal("unproved derived formula accepted")
	}
	r.Sources[len(r.Sources)-1].InputSourceIDs = []string{"surface-a", "surface-b"}
	first := r.Links[0]
	first.FromValue, first.ToValue = 86.4, 86.4
	first.SourceIDs = []string{"surface-a", "cooling-source"}
	second := first
	second.ID, second.SourceIDs = "second-physical-branch", []string{"surface-b", "cooling-source"}
	r.Links = append([]EnergyPathLink{second, first}, r.Links[1:]...)
	if err := epathCheckSQLModelDriverLink(bundle, check); err != nil {
		t.Fatalf("distinct provenance partitions with conserved values rejected: %v", err)
	}
	byID := map[string]EnergyExplanationNode{}
	for _, node := range r.Nodes {
		byID[node.ID] = node
	}
	for _, link := range r.Links {
		if got := epathSQLDriverLinkMatches(byID, link, check.DriverLink); got != (link.FromID == "wall") {
			t.Fatalf("coverage predicate overmatched %s", link.ID)
		}
	}
}

func TestEnergyPathRealSQLDriverLinksEndpointOwnershipMutants(t *testing.T) {
	_, _, checks, original := epathSQLDriverLinksFixture(t)
	check := epathSQLDriverAnnualWallCheck(t, checks)
	for _, test := range []struct {
		name string
		edit func(*EnergyExplanationResult)
	}{
		{"driver contribution moved to load endpoint", func(r *EnergyExplanationResult) {
			r.Nodes[0].SourceIDs = []string{"surface-a"}
			r.Nodes[2].SourceIDs = []string{"cooling-source", "surface-b"}
		}},
		{"same physical branch split by rule", func(r *EnergyExplanationResult) {
			first := r.Links[0]
			first.FromValue, first.ToValue = 86.4, 86.4
			second := first
			second.ID, second.RuleID = "duplicated-rule-branch", "different-rule-text"
			r.Links = append([]EnergyPathLink{first, second}, r.Links[1:]...)
		}},
		{"same physical branch split by explanation", func(r *EnergyExplanationResult) {
			first := r.Links[0]
			first.FromValue, first.ToValue = 86.4, 86.4
			second := first
			second.ID, second.Explanation = "duplicated-explanation-branch", "Different descriptive wording"
			r.Links = append([]EnergyPathLink{first, second}, r.Links[1:]...)
		}},
		{"same physical branch hidden behind derived source alias", func(r *EnergyExplanationResult) {
			r.Sources = append(r.Sources, EnergyDataSource{ID: "same-original-leaves", SourceType: "derived_formula", InputSourceIDs: []string{"surface-a", "surface-b"}})
			first := r.Links[0]
			first.FromValue, first.ToValue = 86.4, 86.4
			second := first
			second.ID, second.SourceIDs = "duplicated-derived-branch", []string{"same-original-leaves", "cooling-source"}
			r.Links = append([]EnergyPathLink{first, second}, r.Links[1:]...)
		}},
	} {
		t.Run(test.name, func(t *testing.T) {
			data, err := json.Marshal(original)
			if err != nil {
				t.Fatal(err)
			}
			candidate, err := epathDecodeOriginalOracleCandidate(strings.NewReader(string(data)))
			if err != nil {
				t.Fatal(err)
			}
			test.edit(&candidate.EnergyExplanation)
			if err := epathCheckSQLModelDriverLink(candidate, check); err == nil {
				t.Fatal("unchanged quantities concealed incorrect physical source ownership")
			}
		})
	}
	// Allocated/derived drivers may legitimately depend on delivered load.
	// Require ownership of their pressure leaves, not disjoint source domains.
	r := &original.EnergyExplanation
	r.Sources = append(r.Sources, EnergyDataSource{ID: "load-aware-derived-driver", SourceType: "derived_formula", InputSourceIDs: []string{"surface-a", "surface-b", "cooling-source"}})
	r.Nodes[0].SourceIDs = []string{"load-aware-derived-driver"}
	r.Links[0].SourceIDs = []string{"load-aware-derived-driver", "cooling-source"}
	if err := epathCheckSQLModelDriverLink(original, check); err != nil {
		t.Fatalf("legitimate derived driver/load overlap rejected: %v", err)
	}
	first := r.Links[0]
	first.FromValue, first.ToValue, first.RelatedPathIDs = 86.4, 86.4, []string{"physical-path-a"}
	second := first
	second.ID, second.RelatedPathIDs = "second-path-branch", []string{"physical-path-b"}
	r.Links = append([]EnergyPathLink{first, second}, r.Links[1:]...)
	if err := epathCheckSQLModelDriverLink(original, check); err != nil {
		t.Fatalf("distinct physical path branches rejected: %v", err)
	}
}

func TestEnergyPathRealSQLDriverLinksCompleteBuildingLoadSources(t *testing.T) {
	// Add a second actual SQL Zone to the small fixture. Office contributes
	// load18/month, surface14.4, People3.6; Lab contributes load2, surface1.6,
	// People0.4. The literal candidate totals are independently 240/192/48.
	path, model := epathSQLModelUnitFixture(t)
	epathOracleEditSQL(t, path, `INSERT INTO Zones VALUES(2,'Lab',1,1);
INSERT INTO Surfaces VALUES(3,'Wall C','Wall',2,0,1);
INSERT INTO ReportDataDictionary VALUES(15,'Sensible Cooling','Lab',0,'Monthly','J','Zone'),(16,'Sensible Heating','Lab',0,'Monthly','J','Zone'),(17,'Surface Exchange','Wall C',0,'Monthly','J','Surface'),(18,'People Gain','Lab',0,'Monthly','J','Zone');
INSERT INTO ReportData SELECT ReportDataIndex+100000,15,TimeIndex,7200000 FROM ReportData WHERE ReportDataDictionaryIndex=10;
INSERT INTO ReportData SELECT ReportDataIndex+100000,16,TimeIndex,0 FROM ReportData WHERE ReportDataDictionaryIndex=11;
INSERT INTO ReportData SELECT ReportDataIndex+100000,17,TimeIndex,-14400000 FROM ReportData WHERE ReportDataDictionaryIndex=12;
INSERT INTO ReportData SELECT ReportDataIndex+100000,18,TimeIndex,3600000 FROM ReportData WHERE ReportDataDictionaryIndex=14;`)
	model.Surface.Source.Keys = append(model.Surface.Source.Keys, "Wall C")
	model.Families[0].Keys = append(model.Families[0].Keys, "Lab")
	model.Families[0].Terms[0].Source.Keys = append(model.Families[0].Terms[0].Source.Keys, "Lab")
	for index := range model.Loads {
		model.Loads[index].Source.Keys = append(model.Loads[index].Source.Keys, "Lab")
	}
	observed, err := epathReadRealSQLOracle(path)
	if err != nil {
		t.Fatal(err)
	}
	frames, err := epathCompileSQLModelFrames(path, observed.Sources, model)
	if err != nil {
		t.Fatal(err)
	}
	var checks epathSQLModelChecks
	if err := epathSQLModelDriverLinkChecks(frames, model, &checks); err != nil {
		t.Fatal(err)
	}
	check := epathSQLDriverAnnualWallCheck(t, checks)
	if !reflect.DeepEqual(check.DriverLink.LoadSources, []int{10, 15}) || !reflect.DeepEqual(check.DriverLink.RequiredLoadSources, []int{10, 15}) || math.Abs(check.DriverLink.Load.Value-240) > 1e-9 || math.Abs(check.Quantity.Value-192) > 1e-9 {
		t.Fatal("independent two-Zone load/source roster was not compiled")
	}
	_, _, _, original := epathSQLDriverLinksFixture(t)
	r := &original.EnergyExplanation
	r.AvailableZones = append(r.AvailableZones, "Lab")
	for _, source := range []EnergyDataSource{
		{ID: "lab-wall", Name: "Surface Exchange", KeyValue: "Wall C"},
		{ID: "lab-people", Name: "People Gain", KeyValue: "Lab"},
		{ID: "lab-cooling", Name: "Sensible Cooling", KeyValue: "Lab"},
	} {
		source.SourceType, source.SourceUnit, source.NormalizedUnit, source.ReportingFrequency = "sql_report_data", "J", "kWh", "Monthly"
		r.Sources = append(r.Sources, source)
	}
	r.Nodes[0].Value, r.Nodes[0].SourceIDs = 192, []string{"surface-a", "surface-b", "lab-wall"}
	r.Nodes[1].Value, r.Nodes[1].SourceIDs = 48, []string{"people-source", "lab-people"}
	r.Nodes[2].Value, r.Nodes[2].SourceIDs = 240, []string{"cooling-source", "lab-cooling"}
	r.Links[0].FromValue, r.Links[0].ToValue = 192, 192
	r.Links[0].SourceIDs = []string{"surface-a", "surface-b", "lab-wall", "cooling-source", "lab-cooling"}
	r.Links[1].FromValue, r.Links[1].ToValue = 48, 48
	r.Links[1].SourceIDs = []string{"people-source", "lab-people", "cooling-source", "lab-cooling"}
	if err := epathCheckSQLModelDriverLink(original, check); err != nil {
		t.Fatalf("complete independent two-Zone provenance rejected: %v", err)
	}
	for _, test := range []struct {
		name string
		edit func(*EnergyExplanationResult)
	}{
		{"missing second load source on endpoint", func(r *EnergyExplanationResult) { r.Nodes[2].SourceIDs = []string{"cooling-source"} }},
		{"missing second load source on link", func(r *EnergyExplanationResult) {
			r.Links[0].SourceIDs = []string{"surface-a", "surface-b", "lab-wall", "cooling-source"}
		}},
		{"missing second load source on both", func(r *EnergyExplanationResult) {
			r.Nodes[2].SourceIDs = []string{"cooling-source"}
			r.Links[0].SourceIDs = []string{"surface-a", "surface-b", "lab-wall", "cooling-source"}
		}},
	} {
		t.Run(test.name, func(t *testing.T) {
			data, err := json.Marshal(original)
			if err != nil {
				t.Fatal(err)
			}
			candidate, err := epathDecodeOriginalOracleCandidate(strings.NewReader(string(data)))
			if err != nil {
				t.Fatal(err)
			}
			test.edit(&candidate.EnergyExplanation)
			if err := epathCheckSQLModelDriverLink(candidate, check); err == nil {
				t.Fatal("full Building load retained with incomplete exact SQL provenance")
			}
		})
	}
	for _, test := range []struct {
		name     string
		loadKWh  float64
		required bool
	}{
		{"reported zero whole Zone load pruned", 0, false},
		{"positive SQL center with zero-containing precision interval", .0001, false},
		{"independently positive interval cannot lose contributor", .0011, true},
	} {
		t.Run(test.name, func(t *testing.T) {
			epathOracleEditSQL(t, path, fmt.Sprintf(`UPDATE ReportData SET Value=%.17g WHERE ReportDataDictionaryIndex=15`, test.loadKWh*3600000))
			observed, err := epathReadRealSQLOracle(path)
			if err != nil {
				t.Fatal(err)
			}
			frames, err := epathCompileSQLModelFrames(path, observed.Sources, model)
			if err != nil {
				t.Fatal(err)
			}
			var checks epathSQLModelChecks
			if err := epathSQLModelDriverLinkChecks(frames, model, &checks); err != nil {
				t.Fatal(err)
			}
			// Omit the whole Lab contribution while retaining original Office
			// values, not values read from the generated expectation/candidate.
			_, _, _, pruned := epathSQLDriverLinksFixture(t)
			pruned.EnergyExplanation.AvailableZones = append(pruned.EnergyExplanation.AvailableZones, "Lab")
			for _, period := range []string{"annual", "M1"} {
				var selected *epathSQLModelCheck
				for index := range checks.Rows {
					item := &checks.Rows[index]
					if item.Item.Scope == "building" && item.Item.Period == period && item.DriverLink.Category == "surface.exterior_walls" && item.DriverLink.Service == "cooling" && item.Item.Target.Field == "fromValue" {
						selected = item
					}
				}
				if selected == nil || !reflect.DeepEqual(selected.DriverLink.LoadSources, []int{10, 15}) {
					t.Fatal("whole-node pruning changed the allowed independent SQL roster")
				}
				wantRequired := []int{10}
				if test.required {
					wantRequired = append(wantRequired, 15)
				}
				if !reflect.DeepEqual(selected.DriverLink.RequiredLoadSources, wantRequired) {
					t.Fatalf("%s required leaves do not follow independent completed intervals: %v", period, selected.DriverLink.RequiredLoadSources)
				}
				err := epathCheckSQLModelDriverLink(pruned, *selected)
				if test.required && err == nil {
					t.Fatalf("%s independently positive load contributor was omitted", period)
				}
				if !test.required && err != nil {
					t.Fatalf("%s proven zero-containing whole-node pruning rejected: %v", period, err)
				}
			}
		})
	}
	t.Run("annual endpoint versus category-specific monthly overlap", func(t *testing.T) {
		// Office's load belongs only to M1, Lab's only to M2. Lab has no
		// surface pressure, so the annual wall branch is solely Office/M1.
		// People spans both months. No candidate value defines these SQL facts.
		epathOracleEditSQL(t, path, `UPDATE ReportData SET Value=CASE WHEN TimeIndex=1 THEN 10800000 ELSE 0 END WHERE ReportDataDictionaryIndex=10;
UPDATE ReportData SET Value=CASE WHEN TimeIndex=2 THEN 7200000 ELSE 0 END WHERE ReportDataDictionaryIndex=15;
UPDATE ReportData SET Value=0 WHERE ReportDataDictionaryIndex=17;`)
		observed, err := epathReadRealSQLOracle(path)
		if err != nil {
			t.Fatal(err)
		}
		frames, err := epathCompileSQLModelFrames(path, observed.Sources, model)
		if err != nil {
			t.Fatal(err)
		}
		var checks epathSQLModelChecks
		if err := epathSQLModelDriverLinkChecks(frames, model, &checks); err != nil {
			t.Fatal(err)
		}
		wallCheck := epathSQLDriverAnnualWallCheck(t, checks)
		if !reflect.DeepEqual(wallCheck.DriverLink.RequiredLoadSources, []int{10, 15}) || !reflect.DeepEqual(wallCheck.DriverLink.RequiredLinkLoadSources["surface.exterior_walls"], []int{10}) || !reflect.DeepEqual(wallCheck.DriverLink.RequiredLinkLoadSources["internal.people"], []int{10, 15}) {
			t.Fatal("independent per-category month overlap was replaced by the annual union")
		}
		data, err := json.Marshal(original)
		if err != nil {
			t.Fatal(err)
		}
		candidate, err := epathDecodeOriginalOracleCandidate(strings.NewReader(string(data)))
		if err != nil {
			t.Fatal(err)
		}
		r := &candidate.EnergyExplanation
		r.Nodes[0].Value, r.Nodes[0].SourceIDs = 14.4, []string{"surface-a", "surface-b"}
		r.Nodes[1].Value, r.Nodes[1].SourceIDs = 5.6, []string{"people-source", "lab-people"}
		r.Nodes[2].Value = 20
		r.Links[0].FromValue, r.Links[0].ToValue = 14.4, 14.4
		r.Links[0].SourceIDs = []string{"surface-a", "surface-b", "cooling-source"}
		r.Links[1].FromValue, r.Links[1].ToValue = 5.6, 5.6
		selected := []epathSQLModelCheck{}
		for _, item := range checks.Rows {
			if item.Item.Scope == "building" && item.Item.Period == "annual" && item.DriverLink.Service == "cooling" && (item.DriverLink.Category == "surface.exterior_walls" || item.DriverLink.Category == "") {
				selected = append(selected, item)
				if err := epathCheckSQLModelDriverLink(candidate, item); err != nil {
					t.Fatalf("non-overlapping positive Lab load was incorrectly required on the annual wall branch: %v", err)
				}
			}
		}
		if len(selected) != 4 {
			t.Fatal("category and all-incoming endpoint checks were not both exercised")
		}
		data, err = json.Marshal(candidate)
		if err != nil {
			t.Fatal(err)
		}
		for _, edit := range []struct {
			name  string
			apply func(*EnergyExplanationResult)
		}{
			{"non-overlap source still required on annual load endpoint", func(r *EnergyExplanationResult) { r.Nodes[2].SourceIDs = []string{"cooling-source"} }},
			{"active-month source cannot be replaced with another month's source", func(r *EnergyExplanationResult) {
				r.Links[0].SourceIDs = []string{"surface-a", "surface-b", "lab-cooling"}
			}},
		} {
			t.Run(edit.name, func(t *testing.T) {
				mutant, err := epathDecodeOriginalOracleCandidate(strings.NewReader(string(data)))
				if err != nil {
					t.Fatal(err)
				}
				edit.apply(&mutant.EnergyExplanation)
				for _, item := range selected {
					if err := epathCheckSQLModelDriverLink(mutant, item); err == nil {
						t.Fatalf("%s lost independent endpoint/month ownership", item.Want.Key)
					}
				}
			})
		}
	})
}

func TestEnergyPathRealSQLDriverLinksDependencyLeaves(t *testing.T) {
	path, model := epathSQLModelUnitFixture(t)
	observed, err := epathReadRealSQLOracle(path)
	if err != nil {
		t.Fatal(err)
	}
	model.Families = append(model.Families,
		epathRealSQLFamily{ID: "derived", Keys: []string{"Office"}, Category: "balance.storage_other", Component: "sensible", Role: "context", Subtract: []string{"surface.total", "people"}},
		epathRealSQLFamily{ID: "nested", Keys: []string{"Office"}, Category: "balance.storage_other", Component: "sensible", Role: "context", Subtract: []string{"derived"}},
	)
	frames, err := epathCompileSQLModelFrames(path, observed.Sources, model)
	if err != nil {
		t.Fatal(err)
	}
	for month := 1; month <= 12; month++ {
		for _, family := range []string{"derived", "nested"} {
			cell := frames.Cells[epathSQLKey("Office", family, month)]
			if !reflect.DeepEqual(cell.SourceIDs, []int{12, 13, 14}) {
				t.Fatalf("lost independently subtracted leaves %s: %v", family, cell.SourceIDs)
			}
		}
		if got := frames.Cells[epathSQLKey("Office", "surface:surface.exterior_walls", month)].SourceIDs; !reflect.DeepEqual(got, []int{12, 13}) {
			t.Fatalf("dependency union mutated source ownership: %v", got)
		}
		if got := frames.Cells[epathSQLKey("Office", "people", month)].Allocated["cooling"].Value; math.Abs(got-3.6) > 1e-12 {
			t.Fatal("source tracking changed allocation math")
		}
	}
}

func TestEnergyPathRealSQLDriverLinksMonthFirstTaxonomy(t *testing.T) {
	frames, model, _, _ := epathSQLDriverLinksFixture(t)
	frames.Cells = map[string]*epathSQLCell{}
	for month := 1; month <= 12; month++ {
		load, exchange := 0.0, 0.0
		if month == 1 {
			load, exchange = 100, 4
		}
		if month == 2 {
			load, exchange = 100, 6
		}
		frames.Loads[epathSQLKey("Office", "cooling", month)] = epathSQLQuantity{Value: load}
		for _, item := range []struct {
			category string
			value    float64
		}{{"surface.interzone", exchange}, {"surface.exterior_walls", load - exchange}} {
			key := epathSQLKey("Office", item.category, month)
			frames.Cells[key] = &epathSQLCell{Zone: "Office", Family: item.category, Category: item.category, Month: month, BuildingVisible: true, SourceIDs: []int{12, 13}, Allocated: map[string]epathSQLQuantity{"cooling": {Value: item.value}, "heating": {}}}
		}
	}
	var checks epathSQLModelChecks
	if err := epathSQLModelDriverLinkChecks(frames, model, &checks); err != nil {
		t.Fatal(err)
	}
	want := map[string]float64{"building/balance.storage_other": 4, "building/interzone.transfer": 6, "building/surface.exterior_walls": 190, "zone/surface.interzone": 10, "zone/surface.exterior_walls": 190}
	for _, check := range checks.Rows {
		if check.Item.Period != "annual" || check.DriverLink.Service != "cooling" || check.Item.Target.Field != "fromValue" || check.DriverLink.Category == "" {
			continue
		}
		key := check.Item.Scope + "/" + check.DriverLink.Category
		value, ok := want[key]
		if !ok || check.Quantity.Value != value {
			t.Fatalf("annual regrouped the completed monthly taxonomy: %s=%g", key, check.Quantity.Value)
		}
		delete(want, key)
	}
	if len(want) > 0 {
		t.Fatalf("missing month-first categories: %v", want)
	}
	for _, check := range checks.Rows {
		if strings.Contains(check.Want.Key, "surface.interzone") && check.Item.Scope == "building" {
			t.Fatal("Zone-only category leaked into Building selector")
		}
	}
}
